CREATE TABLE VENUE(
	ID SERIAL, 
	NAME VARCHAR(255), 
	CITY VARCHAR(255), 
	STATE VARCHAR(255),
	PRIMARY KEY(ID)
);

CREATE SEQUENCE VENUE_SEQUENCE start with 1 increment by 1;
INSERT INTO VENUE(ID, NAME, CITY, STATE) VALUES (VENUE_SEQUENCE.NEXTVAL, 'Wrigley', 'Wrigley', 'Wrigley');

CREATE TABLE EVENTS(
	ID SERIAL, 
	NAME VARCHAR(255), 
	DATE TIMESTAMP,
	VENUE BIGINT,
	PRIMARY KEY(ID)
);

CREATE SEQUENCE EVENTS_SEQUENCE start with 1 increment by 1;
ALTER TABLE EVENTS ADD FOREIGN KEY (VENUE) REFERENCES VENUE(ID);
INSERT INTO EVENTS(ID, NAME, DATE, VENUE) VALUES (EVENTS_SEQUENCE.NEXTVAL, 'Chicago White Sox vs. Chicago Cubs', SYSDATE, VENUE_SEQUENCE.CURRVAL);