
const states = [
    { value: 'AK', name: 'AK' },
    { value: 'AL', name: 'AL' },
    { value: 'AR', name: 'AR' },
    { value: 'AZ', name: 'AZ' },
    { value: 'CA', name: 'CA' },
    { value: 'CO', name: 'CO' },
    { value: 'CT', name: 'CT' },
    { value: 'DC', name: 'DC' },
    { value: 'DE', name: 'DE' },
    { value: 'FL', name: 'FL' },
    { value: 'GA', name: 'GA' },
    { value: 'HI', name: 'HI' },
    { value: 'IA', name: 'IA' },
    { value: 'ID', name: 'ID' },
    { value: 'IL', name: 'IL' },
    { value: 'IN', name: 'IN' },
    { value: 'KS', name: 'KS' },
    { value: 'KY', name: 'KY' },
    { value: 'LA', name: 'LA' },
    { value: 'MA', name: 'MA' },
    { value: 'MD', name: 'MD' },
    { value: 'ME', name: 'ME' },
    { value: 'MI', name: 'MI' },
    { value: 'MN', name: 'MN' },
    { value: 'MO', name: 'MO' },
    { value: 'MS', name: 'MS' },
    { value: 'MT', name: 'MT' },
    { value: 'NC', name: 'NC' },
    { value: 'ND', name: 'ND' },
    { value: 'NE', name: 'NE' },
    { value: 'NH', name: 'NH' },
    { value: 'NJ', name: 'NJ' },
    { value: 'NM', name: 'NM' },
    { value: 'NV', name: 'NV' },
    { value: 'NY', name: 'NY' },
    { value: 'OH', name: 'OH' },
    { value: 'OK', name: 'OK' },
    { value: 'OR', name: 'OR' },
    { value: 'PA', name: 'PA' },
    { value: 'RI', name: 'RI' },
    { value: 'SC', name: 'SC' },
    { value: 'SD', name: 'SD' },
    { value: 'TN', name: 'TN' },
    { value: 'TX', name: 'TX' },
    { value: 'UT', name: 'UT' },
    { value: 'VA', name: 'VA' },
    { value: 'VT', name: 'VT' },
    { value: 'WA', name: 'WA' },
    { value: 'WI', name: 'WI' },
    { value: 'WV', name: 'WV' },
    { value: 'WY', name: 'WY' }
];

export default states;